#' Matching query spectra to existing library
#'
#' The function batch searches unknown MS/MS spectra (written in a mgf file) in a spectral library
#'
#' @param library_type A character precising the type of library. Fast search: "Metabolite" for precompiled GNPS + MASSBANK library; "Private" for precompiled JANSSEN library (2019-9-20); "Public" for drug spectra in public domains (GNPS and MASSBANK, positive mode only); Slower search: "Local" if a customized spectra library is provided
#' @param local_library Customized spectral library. Obligatory if library_type = "Local". A list generated by the function library_generator() or the name of mgf spectral library file
#' @param query_library A list generated by the function library_generator() or the name of mgf spectral library file
#' @param method Character. Method to compare the similarity between query spectrum and library spectra.
#' \itemize{
#'   \item{Fragment:}{ Counting only number of fragment matches}
#'   \item{Simple:}{ Conting number of fragment and neutral loss matches}
#'   \item{Cosine:}{ Cosine similarity score from OrgMassSpecR package.}
#' }
#' @param use.prec Boolean. If set to TRUE, precursor mass (PEPMASS in the mgf file) is used to "pre-query" the library
#' @param ppm_search Numeric. Mass tolerance in ppm for precursor search.
#' @param tops Integer. Number of top compound candidates kept in the output mgf file
#' @param max_peaks Integer. Top most intense peaks kept in eacg query spectrum
#' @param min_relative Numeric between 0.1 and 1. Minimum relative intensity of peaks to not be considered as noise in the query spectrum
#' @param output String. File name of output library with annotation result.
#'
#' @return
#' \itemize{
#'    \item{library_annotated:}{ Library annotated}
#'    \item{sub_extracted:}{ Library object that contain found scans.}
#'    \item{MGF FILE:}{ A MGF file with annotated substructures will be written in user's folder.}
#' }
#' @author Youzhong Liu, \email{Youzhong.Liu@uantwerpen.be}
#'
#' @examples
#' 
#' data(DRUG_THERMO_LIBRARY)
#' 
#' # Search in public database:
#' query = library_search_engine_batch(library_type = "Public", local_library = NULL, 
#' query_library = library2, method = "Simple", use.prec =FALSE)
#'
#' @importFrom MSnbase fData readMgfData
#' @importFrom tools file_ext
#' @importFrom stringr str_replace_all fixed
#' @importFrom OrgMassSpecR SpectrumSimilarity
#'
#' @export

library_search_engine_batch <- function(library_type = c("Metabolite", "Private", "Public", "Local"), 
                         local_library = NULL, query_library=NULL,  
                         method = c("Fragment", "Simple", "Cosine"),
                         use.prec = FALSE, ppm_search = 10, 
                         tops = 5, max_peaks = 200, min_relative = 0.1,  output="annotation.mgf"){
  
  options(stringsAsFactors = FALSE)
  options(warn=-1)

  #################
  ### Check inputs:
  #################
  
  if (!(library_type %in% c("Metabolite", "Private", "Public", "Local"))){
    stop("Library type must be Metabolite, Private, Public or Local!")
  }
  
  if ((library_type=="Local") && is.null(local_library)){
    stop("Please provide the local library!")
  }
  
  if ((library_type=="Local") && is.character(local_library)){
    if (file_ext(library)!="mgf"){
      stop("The file extension of your input library must be mgf!")
  }}
  
  if (is.list(local_library)){
    if (length(local_library)==2 && "complete" %in% names(library)){
      local_library = local_library$complete
    }
    if (length(local_library)!=2 || (!is.list(local_library$sp)) || !is.data.frame(local_library$metadata)){
      stop("Please make sure your input library is a valid output of library_generator()!")
    }
  }
  
  if (library_type=="Local"){
    local_library = library_manager(local_library, query = "MSLEVEL = 1")$LEFT
    local_library = library_manager(local_library, query = paste0("IONMODE = ",ion.mode[1]))$SELECTED
    if (nrow(local_library$metadata)==0){stop("No MS/MS records!")}
    if (nrow(local_library$metadata)>50){
      print("Attention! Spectral search can be slow if a large local library is provided!")
    }
  }
  
  if (is.null(query_library)){
    stop("Please provide an input pseudo-library for batch search!")
  }
  
  if (is.character(query_library)){
    if (file_ext(query_library)!="mgf"){
      stop("The file extension of your input pseudo-library must be mgf!")
    }}
  
  if (is.list(query_library)){
    if (length(query_library)==2 & "complete" %in% names(query_library)){
      query_library = query_library$complete
    }
    if (length(query_library)!=2 || (!is.list(query_library$sp)) || !is.data.frame(query_library$metadata)){
      stop("Please make sure your input library is a valid output of library_generator()!")
    }}
  
  query_library = library_manager(query_library, query = "MSLEVEL = 1")
  query_library = query_library$LEFT
  NT = nrow(query_library$metadata)
  
  if (NT==0){stop("No MS/MS records!")}
  
  #######################
  ### Search one by one :
  #######################
  
  annotation_list =  list()
  estimation_list = rep("0", NT)
  query_metadata = query_library$metadata
  query_mz = as.numeric(query_metadata$PEPMASS)
  
  for (i in 1:NT){
    
    print("Search spectrum:")
    print(i)
    
    query_spectrum = query_library$sp[[i]]

    result = try(library_search_engine(library_type, local_library, query_spectrum, ion.mode = query_metadata$IONMODE[i],
                 method = method, prec_mz = query_mz[i], use.prec, 
                 ppm_search, tops, max_peaks, min_relative, FALSE, FALSE), silent = T)
    
    if (class(result)!="try-error"){
     estimation = result$SELECTED$metadata$ID
    
     if (length(estimation)>0){
       estimation_list[i] = paste0(estimation, collapse = ":")
       annotation_list[[i]] = cbind.data.frame(COMPOUND = estimation, SCORE = result$SCORES)
     } else {
       annotation_list[[i]]= NULL
    }} else {annotation_list[[i]]= NULL}
  }
    
  ##############
  #####Output###
  ##############
  
  query_metadata = cbind.data.frame(query_metadata, OUTPUT_COMPOUND = estimation_list)
  query_library$metadata = query_metadata
  writeMGF2(query_library, con = output)
  
  return(list(library_annotated = query_library, compoud_annotated = annotation_list))
}
  
  