#' Searching and managing the spectral library
#'
#' The function queries and selects or removes scans from the spectral library that satisfy user-defined conditions (query metadata)
#'
#' @param input_library A list generated by the function library_generator() or the name of mgf/msp/RData spectral library file
#' @param query  Vector of characters. Vector of conditions used for querying the library. e.g. c("IONMODE=Positive","PEPMASS=325.19"). The left-hand side must match with the medata items of the searched library.
#' @param logical Character. "AND" for selecting scans that satisfy all conditions, "OR" when selecting records that satisfy at least one condition
#' @param ppm_search Numeric. Mass tolerance in ppm. Only used when searching by precursor mass "PEPMASS=..."
#' @param rt_search Numeric. Retention time tolerance in second (although rt in the query and metadata in min). Only used when searching by retention time "RT=..."
#' @return
#' \itemize{
#'  \item{SELECTED:}{ Library object that only contain selected}
#'  \item{LEFT:}{ Library object that only contain unselected scans}
#' }
#'
#' @examples
#'
#' data(DRUG_THERMO_LIBRARY)
#'
#' # Search library using query command lines:
#' query = library_manager(library2, query=c("IONMODE=Positive", "RT=1.2"), logical="AND", rt_search=6)
#'
#' # Create a new library from query:
#' new_library1 = query$SELECTED
#'
#' # Summary of found compounds:
#' library_reporter(new_library1)
#'
#' # Remove scans from current library according to query:
#' new_library2 = query$LEFT
#'
#' # Add another filter:
#' query = library_manager(new_library1,query=c("IONMODE=Positive","MSLEVEL=2","RT=1.2"))
#' new_library3 = query$SELECTED
#'
#' @export
#'
#' @importFrom MSnbase fData readMgfData
#' @importFrom stringr str_replace_all fixed
#'
library_manager<-function(input_library, query = "", logical = c("AND","OR"), ppm_search = 20, rt_search = 12){

  options(stringsAsFactors = FALSE)
  options(warn=-1)

  logical = match.arg(logical,choices=c("AND","OR"),several.ok = FALSE)
  
  #####################################
  ### Reading from spectral library:###
  #####################################

  metadata = input_library$metadata
  spectrum_list = input_library$sp

  prec_mz = as.numeric(metadata$PEPMASS)
  prec_rt = as.numeric(metadata$RT)
  
  #############################################
  ### Run query expressions and find indexes ##
  #############################################

  if (!is.character(query)){
    stop("Query expression is not valid!")}

  if (query!=""){

    indexes_list = list()
    NI = 0

    for (eps in query){
      eps1 =  str_replace_all(eps,fixed(" "),"") # Remove white space

    # Search pepmass and rt:
      
      if (startsWith(eps1,"PEPMASS=")){
        target_mass = as.numeric(strsplit(eps1,"=")[[1]][2])
        if (!is.na(target_mass)){
          ppm_list = ppm_distance(prec_mz, target_mass)
          indexes = which(ppm_list<=ppm_search)
        }
      } else if (startsWith(eps1,"RT=")){
        target_rt = as.numeric(strsplit(eps1,"=")[[1]][2])
        if (!is.na(target_rt)){
          rtdev_list = abs(target_rt*60-prec_rt*60)
          indexes = which(rtdev_list<=rt_search)
      }} else {

    # Search other things:
      target_variable = strsplit(eps1,"=")[[1]][1]
      target_value = strsplit(eps1,"=")[[1]][2]
      cid = which(colnames(metadata) == target_variable)
      if (length(cid)==1){
        indexes = which(metadata[,cid]==target_value)}}

    # Add valid indexes:

      if (length(indexes)>0){
          NI = NI + 1
          indexes_list[[NI]] = indexes}
    }

    if (logical=="AND"){
      indexes_list = Reduce(intersect,indexes_list)
    }

    if (logical=="OR"){
      indexes_list = Reduce(union,indexes_list)
    }}

  # Output results:

  NN = 1:length(spectrum_list)
  left_list = setdiff(NN, indexes_list)

  SELECTED_LIBRARY = LEFT_LIBRARY = input_library
  SELECTED_LIBRARY$sp = input_library$sp[indexes_list]
  SELECTED_LIBRARY$metadata = input_library$metadata[indexes_list,,drop=FALSE]
  LEFT_LIBRARY$sp = input_library$sp[left_list]
  LEFT_LIBRARY$metadata = input_library$metadata[left_list,,drop=FALSE]

  return(list(SELECTED = SELECTED_LIBRARY,
              LEFT = LEFT_LIBRARY))
}

#########################
### Internal functions:##
#########################

# ppm error calculation:

ppm_distance<-function(x,y){
  x = as.numeric(x)
  y = as.numeric(y)
  if (y>100){
    ppm = abs((x-y))/y*1000000
  } else {
    ppm = abs(x-y)
    ppm[ppm<0.01]=0
  }
  return(ppm)
}


