#' Generating a summary of the spectral library
#'
#' The function generates a report from input spectral library
#'
#' @param input_library A list generated by the function library_generator() or the name of mgf/msp/RData spectral library file
#' @export
#'
#' @examples
#'
#' data(DRUG_THERMO_LIBRARY)
#' library_reporter(library2)
#'
#' @importFrom MSnbase fData readMgfData
#'
#'
library_reporter<-function(input_library){

  options(stringsAsFactors = FALSE)
  options(warn=-1)

  #####################################
  ### Reading from spectral library:###
  #####################################

  input_library = library_reader(input_library)
  metadata = input_library$metadata
  spectrum_list = input_library$sp

  prec_mz = as.numeric(metadata$PEPMASS)
  prec_rt = as.numeric(metadata$RT)
  IDlist = metadata$ID
  IDs = unique(IDlist)

  ####################
  ### Basic summaries:
  ####################

  MS1_num = sum(metadata$MSLEVEL==1)
  MS2_num = sum(metadata$MSLEVEL==2)
  cat("The library contains", MS1_num, "MS1 scans and", MS2_num, "MS2 scans of", length(IDs), "compounds.")
  cat("\n")

  valid_2 = 0
  valid_1_2 = 0
  for (id in IDs){
    sub_levels = metadata$MSLEVEL[which(IDlist==id)]
    if (2 %in% sub_levels){valid_2 = valid_2 +1}
    if ((1 %in% sub_levels) & (2 %in% sub_levels)){valid_1_2 = valid_1_2 +1}}
  cat(valid_1_2, "compounds possess both MS1 and MS2 scans.")
  cat("\n")
  cat(valid_2, "compounds hold MS2 scans.")
  cat("\n")
}
