#' Generate aligned fragment and neutral loss matrix from MS2 spectral library
#'
#' The function reduces the spectral library to improve search efficiency
#'
#' @param input_library A list generated by the function library_generator() or the name of mgf/msp/RData spectral library file
#' @param mz_window  m/z tolerance window (in da) for spectra alignment
#' 
#' @export
#'
#' @importFrom tools file_ext
#' 
library2matrix<-function(input_library, consensus_window = 0.02){
  
  options(stringsAsFactors = FALSE)
  options(warn=-1)

  ####################################
  ### Read and check input library:###
  ####################################
  
  if (is.character(input_library)){
      if (file_ext(input_library)!="mgf" & file_ext(input_library)!="msp" & file_ext(input_library)!="RData"){
        stop("The input library must be mgf, msp or RData format!")
      }
  }
  
  if (is.character(input_library)){
    if (file_ext(input_library)=="mgf"){
      input_library = readMGF2(input_library)}
    if (file_ext(input_library)=="RData"){
      input_library = load_object(input_library)}
    if (file_ext(input_library)=="msp"){
      input_library = readMSP2(input_library)}
  }
  
  if (!is.null(input_library)){
    if (length(input_library)==2 & "complete" %in% names(input_library)){
      input_library = input_library$complete
    }
    if (length(input_library)!=2 || (!is.list(input_library$sp)) || !is.data.frame(input_library$metadata)){
      stop("Please make sure your input library is a valid output of library_generator()!")
    }
    
    input_library = library_manager(input_library, query = "MSLEVEL=2")$SELECTED
    
    if (nrow(input_library$metadata)==0){return(NULL)}
    
    if (nrow(input_library$metadata) ==1){
      
      frags =  input_library$sp[[1]][,1]
      ints =  input_library$sp[[1]][,2]
      nls = as.numeric(input_library$metadata$PEPMASS)-frags
      FID = paste0("Frag_", 1:length(frags))
      NID = paste0("Nloss_", 1:length(nls))
      
      sp_profile =  nl_profile = t(t(ints))
      colnames(sp_profile) = colnames(nl_profile) = input_library$metadata$ID
      sp_feature =  cbind.data.frame(FID = FID, Mass = frags)
      nl_feature =  cbind.data.frame(FID = NID, Mass = nls)
      
      return(list(ref_lib = input_library, sp_profile=sp_profile, sp_feature=sp_feature,nl_profile=nl_profile, nl_feature= nl_feature))
    }
    
    splist = input_library$sp
    metadata = input_library$metadata
    IDlist = metadata$ID
    NM = nrow(metadata)
  } else {stop("Please provide input library!")} 
  
  ############################
  ### Neutral loss spectra:###
  ############################
  
  nllist = list()
  
  for (i in 1:NM){
    sp = splist[[i]]
    prec.mz = as.numeric(metadata$PEPMASS[i])
    nl = cbind(prec.mz - sp[,1], sp[,2])
    nl = nl[nl[,1]>2,,drop=FALSE]
    nl = nl[order(nl[,1]),,drop=FALSE]
    nllist[[i]] = nl
  }  

  #####################
  ### Align spectra:###
  #####################
  
  sp_aligned = average_spectrum(splist, mz_window = consensus_window)
  sp_profile = sp_aligned$I_matrix
  FID = paste0("Frag_", 1:nrow(sp_profile))
  rownames(sp_profile) = FID
  colnames(sp_profile) = IDlist
  sp_feature = data.frame(FID = FID, Mass = sp_aligned$new_spectrum[,1])
    
  nl_aligned = average_spectrum(nllist, mz_window = consensus_window)
  nl_profile = nl_aligned$I_matrix
  NID = paste0("Nloss_", 1:nrow(nl_profile))
  rownames(nl_profile) = NID
  colnames(nl_profile) = IDlist
  nl_feature = data.frame(NID = NID, Mass = nl_aligned$new_spectrum[,1])

  ###############################
  ### Reduce Existing Library####
  ###############################
  
  colnames(sp_feature) = colnames(nl_feature) = c("ID", "Mass")
  
  db_profile = rbind(sp_profile, nl_profile)
  db_feature = cbind(rbind(sp_feature, nl_feature), Type = c(rep("Frag", nrow(sp_feature)), rep("Nloss", nrow(nl_feature))))
  
  valid = which(apply(db_profile, 1, sum)>0)
  db_profile = db_profile[valid,,drop=FALSE]
  db_feature = db_feature[valid,,drop=FALSE]
  
  return(list(ref_lib = input_library, db_profile=db_profile, db_feature=db_feature))
}  
  
######################
### Internal function:
######################

load_object <- function(file) {
  tmp <- new.env()
  load(file = file, envir = tmp)
  tmp[[ls(tmp)[1]]]
}